version: "3"

services:

  node:
    build: ./node
    image: carlososuna86/hello-gulp:node
  nginx:
    build: ./nginx
    image: carlososuna86/hello-gulp:nginx

  app:
    build: ./app
    image: carlososuna86/hello-gulp:app
    expose:
     - '8000'
    networks:
      carlososuna86.info:

  proxy:
    build: ./proxy
    image: carlososuna86/hello-gulp:proxy
    volumes:
     - ./proxy/config/conf.d:/etc/nginx/conf.d
     - ./proxy/config/ssl:/etc/ssl
    ports:
     - '${HTTP_PORT}:80'
     - '${HTTPS_PORT}:443'
    depends_on:
     - app
    networks:
      carlososuna86.info:

networks:
  carlososuna86.info:

