version: "3"

services:

  node:
    build: ./node
    image: carlososuna86/hello-gulp:node
    expose:
     - '8000'

  proxy:
    build: ./proxy
    image: carlososuna86/hello-gulp:proxy
    volumes:
     - ./proxy/config/conf.d:/etc/nginx/conf.d
     - ./proxy/config/ssl:/etc/ssl
    ports:
     - '${HTTP_PORT}:80'
     - '${HTTPS_PORT}:443'
    links:
     - node
    depends_on:
     - node
